export const API_URL =
  "https://run.mocky.io/v3/9d71cb03-a9f9-4d70-bae2-9d3adaa1cfe7";

export const FIFA_DATA = {
  stadium: [
    {
      id: "1",
      name: "Luzhniki Stadium",
      capacity: "78,011",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "2",
      name: "Otkritie Arena",
      capacity: "44,190",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "3",
      name: "Krestovsky Stadium",
      capacity: "64,468",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "4",
      name: "Fisht Olympic Stadium",
      capacity: "44,287",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "5",
      name: "Volgograd Arena",
      capacity: "43,713",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "6",
      name: "Rostov Arena",
      capacity: "43,472",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "7",
      name: "Nizhny Novgorod Stadium",
      capacity: "43,319",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "8",
      name: "Kazan Arena",
      capacity: "42,873",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "9",
      name: "Samara Arena",
      capacity: "41,970",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "10",
      name: "Mordovia Arena",
      capacity: "41,685",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "11",
      name: "Kaliningrad Stadium",
      capacity: "33,973",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
    {
      id: "12",
      name: "Central Stadium",
      capacity: "33,061",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png",
    },
  ],
  GroupPhase: [
    {
      A: [
        {
          id: "1",
          name: "Uruguay",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "2",
          name: "Russia (H)",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "3",
          name: "Saudi Arabia",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "4",
          name: "Egypt",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
      ],
    },
    {
      B: [
        {
          id: "1",
          name: "Spain",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "2",
          name: "Portugal",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "3",
          name: "Iran",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "4",
          name: "Morocco",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
      ],
    },
    {
      C: [
        {
          id: "1",
          name: "France",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "2",
          name: "Denmark",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "3",
          name: "Peru",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "4",
          name: "Australia",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
      ],
    },
    {
      D: [
        {
          id: "1",
          name: "Croatia",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "2",
          name: "Argentina",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "3",
          name: "Nigeria",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
        {
          id: "4",
          name: "Iceland",
          logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
        },
      ],
    },
  ],
  KnockoutPhase: [
    {
      id: "m1",
      nameteam1: "Uruguay",
      nameteam2: "Portugal",
      goalTeam1: 2,
      goalTeam2: 0,
      date: "30 Jun",
      location: "Kazan",
      position: { x: 50, y: 20 },
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Brazil_%281889%E2%80%931960%29.svg/22px-Flag_of_Brazil_%281889%E2%80%931960%29.svg.png",
    },
    {
      id: "m2",
      nameteam1: "France",
      nameteam2: "Argentina",
      goalTeam1: 4,
      goalTeam2: 3,
      date: "2 July",
      location: "Samara",
      position: { x: 50, y: 100 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m3",
      nameteam1: "Brazil",
      nameteam2: "Mexico",
      goalTeam1: 2,
      goalTeam2: 0,
      date: "2 July",
      location: "Rostov-on-Don",
      position: { x: 50, y: 180 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m4",
      nameteam1: "Belgium",
      nameteam2: "Japan",
      goalTeam1: 3,
      goalTeam2: 2,
      date: "1 July",
      location: "Moscow",
      position: { x: 50, y: 260 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m5",
      nameteam1: "Spain",
      nameteam2: "Russia",
      goalTeam1: 1,
      goalTeam2: 1,
      date: "1 July",
      location: "Rostov-on-Don",
      position: { x: 50, y: 340 },
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Brazil_%281889%E2%80%931960%29.svg/22px-Flag_of_Brazil_%281889%E2%80%931960%29.svg.png",
    },
    {
      id: "m6",
      nameteam1: "Croatia",
      nameteam2: "Denmark",
      goalTeam1: 1,
      goalTeam2: 1,
      date: "3 July",
      location: "Saint Peterberg",
      position: { x: 50, y: 420 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m7",
      nameteam1: "Sweden",
      nameteam2: "Switzerland",
      goalTeam1: 1,
      goalTeam2: 0,
      date: "3 July",
      location: "Moscow",
      position: { x: 50, y: 500 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m8",
      nameteam1: "Colombia",
      nameteam2: "England",
      goalTeam1: 1,
      goalTeam2: 1,
      date: "1 July",
      location: "Rostov-on-Don",
      position: { x: 50, y: 580 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m9",
      nameteam1: "Urugway",
      nameteam2: "France",
      goalTeam1: 0,
      goalTeam2: 2,
      date: "6 July",
      location: "Nizhny",
      position: { x: 240, y: 60 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m10",
      nameteam1: "Brazil",
      nameteam2: "Belgium",
      goalTeam1: 1,
      goalTeam2: 2,
      date: "6 July",
      location: "Kazan",
      position: { x: 240, y: 220 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m11",
      nameteam1: "Russia",
      nameteam2: "Croatia",
      goalTeam1: 2,
      goalTeam2: 2,
      date: "7 July",
      location: "Sochi",
      position: { x: 240, y: 370 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m12",
      nameteam1: "Swedean",
      nameteam2: "England",
      goalTeam1: 0,
      goalTeam2: 2,
      date: "7 July",
      location: "Kazan",
      position: { x: 240, y: 550 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m13",
      nameteam1: "France",
      nameteam2: "Belgium",
      goalTeam1: 1,
      goalTeam2: 0,
      date: "10 July",
      location: "Saint Peterberg",
      position: { x: 440, y: 140 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m14",
      nameteam1: "Croatia",
      nameteam2: "England",
      goalTeam1: 2,
      goalTeam2: 1,
      date: "11 July",
      location: "Moscow",
      position: { x: 440, y: 440 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "m15",
      nameteam1: "France",
      nameteam2: "Croatia",
      goalTeam1: 4,
      goalTeam2: 2,
      date: "15 July",
      location: "Moscow",
      position: { x: 530, y: 280 },
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    // {
    //   id: "m16",
    //   nameteam1: "Brazil",
    //   nameteam2: "Belgium",
    //   goalTeam1: 1,
    //   goalTeam2: 2,
    //   date: "6 July",
    //   location: "Kazan",
    //   position: { x: 640, y: 280 },
    // },
    // {
    //   id: "t9",
    //   nameteam1: "Spain",
    //   nameteam2: "Russia",
    //   goalTeam1: 1,
    //   goalTeam2: 1,
    //   date: "1 July",
    //   location: "Rostov-on-Don",
    // },
    // {
    //   id: "t10",
    //   nameteam1: "Spain",
    //   nameteam2: "Russia",
    //   goalTeam1: 1,
    //   goalTeam2: 1,
    //   date: "1 July",
    //   location: "Rostov-on-Don",
    // },
    // {
    //   id: "t11",
    //   nameteam1: "Spain",
    //   nameteam2: "Russia",
    //   goalTeam1: 1,
    //   goalTeam2: 1,
    //   date: "1 July",
    //   location: "Rostov-on-Don",
    // },
    // {
    //   id: "t12",
    //   nameteam1: "Spain",
    //   nameteam2: "Russia",
    //   goalTeam1: 1,
    //   goalTeam2: 1,
    //   date: "1 July",
    //   location: "Rostov-on-Don",
    // },
    // {
    //   id: "t13",
    //   nameteam1: "Spain",
    //   nameteam2: "Russia",
    //   goalTeam1: 1,
    //   goalTeam2: 1,
    //   date: "1 July",
    //   location: "Rostov-on-Don",
    // },
    // {
    //   id: "t14",
    //   name: "Switzerland",
    // },
    // {
    //   id: "t15",
    //   name: "Colombia",
    // },
    // {
    //   id: "t16",
    //   name: "England",
    // },
  ],
  Teams: [
    {
      id: "t1",
      name: "Uruguay",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Brazil_%281889%E2%80%931960%29.svg/22px-Flag_of_Brazil_%281889%E2%80%931960%29.svg.png",
      description: "This is the",
    },
    {
      id: "t2",
      name: "Portugal",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
      description: "This is the",
    },
    {
      id: "t3",
      name: "France",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Brazil_%281889%E2%80%931960%29.svg/22px-Flag_of_Brazil_%281889%E2%80%931960%29.svg.png",
    },
    {
      id: "t4",
      name: "Argentina",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t5",
      name: "Brazil",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t6",
      name: "Mexico",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t7",
      name: "Belgium",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t8",
      name: "Japan",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t9",
      name: "Spain",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t10",
      name: "Russia",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t11",
      name: "Croatia",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t12",
      name: "Denmark",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t13",
      name: "Sweden",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t14",
      name: "Switzerland",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t15",
      name: "Colombia",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
    {
      id: "t16",
      name: "England",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png",
    },
  ],
};
